import React, { useState, useEffect } from 'react';
import { stockService } from '../../services/stockService';
import { InventoryHealthScore } from '../../types';
import { TrendingUp, Zap, CheckCircle2 } from 'lucide-react';
import { InventoryHealthGauge } from '../dashboard/InventoryHealthGauge';

export const InsightsView: React.FC = () => {
  const [health, setHealth] = useState<InventoryHealthScore | null>(null);

  useEffect(() => {
    stockService.calculateInventoryHealth().then(setHealth);
  }, []);

  return (
    <div className="space-y-6">
      <div className="pb-2">
        <div className="flex items-center gap-2">
          <TrendingUp className="w-5 h-5 text-emerald-400" />
          <h1 className="text-xl sm:text-2xl font-bold tracking-tight text-white">
            Inventory Health & Operational Insights
          </h1>
        </div>
        <p className="text-xs text-slate-400 mt-1">
          Algorithmic stockout risk detection, safety buffer analysis, and replenishment telemetry
        </p>
      </div>

      {health && (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          <div className="lg:col-span-1">
            <InventoryHealthGauge health={health} />
          </div>

          <div className="lg:col-span-2 glass-panel rounded-2xl p-6 border border-slate-800 space-y-4">
            <h3 className="text-base font-bold text-white flex items-center gap-2">
              <Zap className="w-5 h-5 text-amber-400" />
              Automated AI Recommendations
            </h3>
            <p className="text-xs text-slate-400">
              Generated by the StockSense calculation engine based on active depletion rates and lead times:
            </p>

            <div className="space-y-3 pt-2">
              {health.recommendations.map((rec, idx) => (
                <div
                  key={idx}
                  className="p-3.5 rounded-xl bg-slate-900/60 border border-slate-800 flex items-start gap-3 text-xs text-slate-200"
                >
                  <CheckCircle2 className="w-4 h-4 text-emerald-400 mt-0.5 flex-shrink-0" />
                  <div className="flex-1">
                    <span className="font-semibold text-white block mb-0.5">Priority Directive #{idx + 1}</span>
                    <span className="text-slate-300">{rec}</span>
                  </div>
                </div>
              ))}
            </div>

            <div className="p-4 rounded-xl bg-emerald-950/20 border border-emerald-500/30 text-xs text-emerald-300 space-y-1 mt-4">
              <strong className="block text-emerald-200">Stock Formula Invariant Guarantee:</strong>
              <p className="text-[11px] leading-relaxed">
                Current Stock is mathematically validated through <code className="font-mono text-emerald-400 font-bold">Opening + Receipts - Deliveries + Transfer In - Transfer Out ± Adjustments</code>. Every transaction is checked with ACID semantics to ensure zero ghost units and negative inventory prevention.
              </p>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
